const xmlns = "http://www.w3.org/2000/svg";
const fontfamily = "verdana";
const fontsize = 12;
const fontsizeoffset = 18;
const polomer = 18;
const velkost = 36;
const posunutie_suradnic = 20;
const arrowHeadSize = 9;
const vahaoffset = 10;
const tokenpolomer = 3;
const tokenposuv = 7;
const maxwidth = 10000;
const maxheight = 5000;
const minwidth = 640;
const minheight = 360;
const korekcia = 0.75 * fontsize;
const gridstep = 2 * posunutie_suradnic;
const maxx = maxwidth - posunutie_suradnic;
const maxy = maxheight - posunutie_suradnic;

var sirkatextu = 0;
var previousStatus;
var originFile;
var hranabymove;
var kresli_sa_hrana = 0;
var source_hrany;
var pocetmousedown = 0;
var posuva_sa_hrana = 0;
var pocetmousedownposuv = 0;
var pocetmousedownposuvtran = 0;
var pocetmousedownposuvplace = 0;
var posuvanahrana;
var hybesaprechod = 0;
var hybesamiesto = 0;
var movedprechod;
var movedmiesto;
var id = 0;
var text = "";
var menofilu = "newmodel.xml";
var downloadLink;
var appwidth = 10000;
var appheight = 5000;
var modal;
var shade;
var insidemodal;
var helptext;
var processdata = [];
var arc_for_data;
var indexbodu;